WIP Fixes fmu properties update
Vizzuality/fti_api pull request #234
Opened 2021-06-01 10:07 UTC by develaper

Here I am trying to fixs the lack of sync between the information stored in the properties of some Fmus(forest management units).
_fmu.rb_
`has_one :fmu_operator, ->{ where(current: true) }`
`has_one :operator, through: :fmu_operator`

and its properties should look like this:
`properties['company_na'] = operator&.name`
`properties['operator_id'] = operator&.id`

2021-06-01 15:42 UTC, tsubik reviewed
Hmm, I wonder why All geometeries are updated when geojson changed and not just the changed one.

2021-06-01 15:42 UTC, tsubik commented on app/models/fmu.rb
> +    self.properties
Do you need to return properties here?

2021-06-01 15:53 UTC, tsubik commented
Maybe executing that query on ActiveRecord::Base in after_save running in not the same transaction. Maybe moving `update_geometry` to `after_commit` will helped, but then `geojson_changed?` won't be available, there is `previous_changes` hash for this.

2021-06-01 15:59 UTC, tsubik commented
Also when using `after_commit` and `previous_changes` the hash could not provide correct changes in `if` statement, when used with lambda like this `-> { previous_changes['foo'].present? }` just saing that this Rails version is buggy, and it worked for me when using `proc` instead, or checking the change in the callback message.

2021-06-21 16:39 UTC, tsubik commented on app/models/fmu.rb
> +  def properties
I would rename that to `geojson_properties`. I hope that will be performant enough, but yeah this is aggressive caching, so maybe it will be ok

2021-06-21 16:56 UTC, tsubik commented on app/models/fmu.rb
> +    temp_properties['observations'] = self.active_observations.reload.uniq.count
I'm not sure if that will work correctly with our aggressive caching, `active_observation` count can change, but the cached FMUs will still return old value. There could be millions problems like this in this codebase actually, this is not related with just this task.

2021-06-21 16:57 UTC, tsubik commented on app/models/fmu.rb
> +    temp_properties['observations'] = self.active_observations.reload.uniq.count
Maybe we should periodically clean up cache.

2021-06-21 16:59 UTC, tsubik requested changes
I think I saw usage of `properties` also in `calculate_current` fmu_operator model. That needs to be removed as well.

2021-06-22 15:07 UTC, agnessa commented on app/models/fmu.rb
>          where fmus.id = g.id;
As far as I can tell this query affects all fmus, not sure why that would be needed after an update of an individual records, but it answers the question why other records are affected. I imagine the reason it is called this way is to make use of the lateral join, which allows to easily call ST_GeomFromGeoJSON and update in a single query. But why for all records - no idea.

2021-07-08 13:32 UTC, develaper commented on app/models/fmu.rb
> +    self.properties
nope. Thanks

2021-07-08 13:41 UTC, develaper commented on app/models/fmu.rb
>          where fmus.id = g.id;
After checking a few times the code base I couldn't find a place where the properties of the geometry can be updated. Meaning that the api gets a request or from the admin panel. Those properties that are only reflected in the geometry.properties, like centroid, were set when the geometry was imported into the DB. Since then `def update_geometry` is called only in the callback . At this callback we only update properties that are actually already reflected in fmu.properties. That's why I don't see the point at all in updating the geometry properties. What do you think?

2021-07-09 06:39 UTC, tsubik requested changes

2021-07-09 06:39 UTC, tsubik commented on app/models/fmu.rb
>          where fmus.id = g.id;
I also don't know why this query is affecting all fmus. Should that be only for the updated one?

2021-07-09 06:39 UTC, tsubik commented on app/models/fmu.rb
> +    properties['company_na'] = operator&.name
I wonder if we cannot just merge update_properties with update_geojson, and save ALL properties, just saving in two places.

2021-07-09 06:39 UTC, tsubik commented on app/models/fmu.rb
>          where fmus.id = g.id;
Is there any other place to update properties? I think there is not, only `update_properties` callback, but it only updates 2 of them, so I think you can remove it, but you need to update all properties like geojson in that callback.

2021-07-09 15:27 UTC, develaper commented on app/models/fmu.rb
>          where fmus.id = g.id;
I have discarded removing duplicated "properties". It was not going to work for the front end. Then properties is updated, then geojson[" properties"] is merged with properties updated.
I have changed the query in update_geometry to work only over the current fmu. I don't see any reason to go over all the fmus neither.

2021-07-12 07:22 UTC, agnessa approved these changes

2021-07-12 11:43 UTC, tsubik commented
One test is failing otherwise looks good :+1:

2021-07-13 13:39 UTC, merged